# Starter pipeline
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  inputs:
    command: 'custom'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(48faf7e9-23de-4e6e-9619-9e10f5b21273)'
    appType: 'webApp'
    WebAppName: 'busquedaPaises'
    packageForLinux: '/Users/erickgarcia/Documents/GitHub/appBuscarPaises-ExamenFinal/dist'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
